# Generated by Django 5.1.4 on 2026-05-27 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxPlacementTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_line', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('test_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('checking', 'Checking'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliverability_inbox_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxPlacementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('seed_email', models.CharField(max_length=255)),
                ('placement', models.CharField(choices=[('inbox', 'Inbox'), ('spam', 'Spam/Junk'), ('missing', 'Not found')], default='missing', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('raw_headers', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='deliverability.inboxplacementtest')),
            ],
            options={
                'db_table': 'deliverability_inbox_result',
                'unique_together': {('test', 'seed_email')},
            },
        ),
    ]
