# Generated by Django 5.1.4 on 2026-06-02 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('blacklisted_on', models.JSONField(default=list)),
                ('spf_found', models.BooleanField(null=True)),
                ('dmarc_found', models.BooleanField(null=True)),
                ('dkim_found', models.BooleanField(null=True)),
                ('mx_found', models.BooleanField(null=True)),
                ('reputation_score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliverability_monitored_domain',
                'ordering': ['domain'],
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='DomainReputationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('blacklisted_on', models.JSONField(default=list)),
                ('spf_found', models.BooleanField(null=True)),
                ('dmarc_found', models.BooleanField(null=True)),
                ('dkim_found', models.BooleanField(null=True)),
                ('mx_found', models.BooleanField(null=True)),
                ('reputation_score', models.IntegerField(null=True)),
                ('monitored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='deliverability.monitoreddomain')),
            ],
            options={
                'db_table': 'deliverability_domain_snapshot',
                'ordering': ['-checked_at'],
            },
        ),
    ]
