# Generated by Django 6.0.5 on 2026-05-25 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('email_column', models.CharField(blank=True, max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('risky_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('deep_checks_made', models.IntegerField(default=0)),
                ('result_file_path', models.CharField(blank=True, max_length=1000)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_bulk_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=320)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('risky', 'Risky'), ('unknown', 'Unknown')], max_length=20)),
                ('sub_status', models.CharField(blank=True, max_length=50)),
                ('score', models.SmallIntegerField(default=0)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_role_based', models.BooleanField(default=False)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('is_free_email', models.BooleanField(default=False)),
                ('mx_found', models.BooleanField(default=False)),
                ('smtp_valid', models.BooleanField(null=True)),
                ('mx_record', models.CharField(blank=True, max_length=255)),
                ('deep_check_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='verification.bulkjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['user', '-created_at'], name='verificatio_user_id_1530cc_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationresult',
            index=models.Index(fields=['user', '-created_at'], name='verificatio_user_id_c25af9_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationresult',
            index=models.Index(fields=['job', 'status'], name='verificatio_job_id_1a35b7_idx'),
        ),
    ]
