# Generated by Django 5.1.4 on 2026-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationresult',
            name='elv_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='esp',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
