# Generated by Django 5.1.4 on 2026-05-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_add_esp_elv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationresult',
            name='elv_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='esp',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='verificationresult',
            name='mx_record',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
