# Generated by Django 5.1.4 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_fix_nullable_charfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjob',
            name='health_advice',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bulkjob',
            name='health_grade',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
