# Generated by Django 5.1.4 on 2026-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_add_health_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
