# Generated by Django 5.1.4 on 2026-05-26 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_id', models.CharField(max_length=100, unique=True)),
                ('charge_code', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(max_length=20)),
                ('billing_period', models.CharField(max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_to_add', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_coinbase_charge',
                'ordering': ['-created_at'],
            },
        ),
    ]
