# Generated by Django 5.1.4 on 2026-05-27 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_coinbasecharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPaymentsInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('invoice_url', models.URLField(max_length=500)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('plan', models.CharField(max_length=20)),
                ('billing_period', models.CharField(max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_to_add', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('failed', 'Failed'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nowpayments_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_nowpayments_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
