# Generated by Django 5.1.4 on 2026-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_nowpaymentsinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowpaymentsinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('pack', 'Credit Pack')], default='plan', max_length=10),
        ),
        migrations.AlterField(
            model_name='nowpaymentsinvoice',
            name='billing_period',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
