# Generated by Django 5.1.4 on 2026-06-24 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_invoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DodoPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('checkout_url', models.URLField(max_length=500)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('invoice_type', models.CharField(choices=[('plan', 'Plan'), ('pack', 'Credit Pack')], default='plan', max_length=10)),
                ('plan', models.CharField(max_length=20)),
                ('billing_period', models.CharField(blank=True, max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_to_add', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodo_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_dodo_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='NowPaymentsInvoice',
        ),
    ]
