# Generated by Django 5.1.4 on 2026-06-24 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_dodopayment_delete_nowpaymentsinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('erc20', 'Ethereum (ERC20)'), ('bep20', 'BSC (BEP20)'), ('trc20', 'TRON (TRC20)')], max_length=10)),
                ('wallet_address', models.CharField(max_length=120)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_type', models.CharField(choices=[('plan', 'Plan'), ('pack', 'Credit Pack')], default='plan', max_length=10)),
                ('plan', models.CharField(max_length=20)),
                ('billing_period', models.CharField(blank=True, max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_to_add', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_crypto_deposit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DodoPayment',
        ),
    ]
