// Deliverability authority cluster. Spread into BLOG_POSTS.
// Pillar + authentication + reputation + bounce/SMTP supporting articles.
// Each links to the relevant free tool and up to the pillar for topical authority.

export const DELIVERABILITY_CLUSTER = [
  // ── PILLAR ────────────────────────────────────────────────────────────────
  {
    slug: 'email-deliverability-guide',
    keyword: 'Email Deliverability',
    title: 'Email Deliverability: The Complete Guide (2026) | BounceTrap',
    metaDescription: 'The complete guide to email deliverability — authentication, reputation, list hygiene and inbox placement. Learn how to keep your emails out of spam.',
    h1: 'The Complete Guide to Email Deliverability',
    readTime: '9 min read',
    publishedAt: '2026-06-04',
    intro: 'Email deliverability is the ability to land your emails in the inbox rather than the spam folder or a bounce. It is the sum of three things: proving who you are (authentication), having a good history (reputation), and sending to real, engaged people (list quality). This guide covers all three and links to the tools and deep-dives for each.',
    sections: [
      {
        heading: 'The three pillars of deliverability',
        paragraphs: ['Every deliverability problem traces back to one of three areas. Get all three right and your inbox placement takes care of itself.'],
        list: [
          'Authentication — SPF, DKIM and DMARC prove your mail is really from you',
          'Reputation — your domain and IP sending history, and blacklist status',
          'List quality — verified, engaged recipients with low bounces and complaints',
        ],
      },
      {
        heading: '1. Authenticate your domain',
        paragraphs: ['Without SPF, DKIM and DMARC, mailbox providers cannot trust your mail and will filter it. Set up all three, then verify them with our free checkers. Start with our guides on what SPF, DKIM and DMARC are and how to configure each.'],
      },
      {
        heading: '2. Protect your reputation',
        paragraphs: ['Your sender reputation is built on history: bounce rates, spam complaints, and whether you hit spam traps. Monitor your domain reputation and blacklist status, and warm up new domains slowly before sending at volume.'],
      },
      {
        heading: '3. Keep your list clean',
        paragraphs: ['Sending to invalid addresses causes bounces that wreck your reputation. Verify your list before every send to remove invalid, disposable and risky addresses. This single habit prevents most deliverability problems before they start.'],
      },
      {
        heading: 'Why are my emails going to spam?',
        paragraphs: ['If your mail is hitting spam, work through the pillars in order: confirm SPF/DKIM/DMARC pass, check you are not blacklisted, then verify your list quality. Most spam-folder problems are caused by missing authentication or a dirty list.'],
      },
    ],
    faqs: [
      { q: 'What is a good email deliverability rate?', a: 'Aim for 95%+ of sent emails reaching the inbox. Below 90% signals authentication, reputation or list-quality problems worth investigating.' },
      { q: 'How do I improve email deliverability fast?', a: 'The quickest win is verifying your list to cut bounces, followed by confirming SPF, DKIM and DMARC are correctly set up.' },
    ],
  },

  // ── AUTHENTICATION ──────────────────────────────────────────────────────
  {
    slug: 'what-is-spf',
    keyword: 'What Is SPF',
    title: 'What Is SPF? Sender Policy Framework Explained | BounceTrap',
    metaDescription: 'What is an SPF record and why does it matter for email deliverability? A plain-English guide to Sender Policy Framework, with a free SPF checker.',
    h1: 'What Is SPF (Sender Policy Framework)?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'SPF, or Sender Policy Framework, is a DNS record that lists which mail servers are allowed to send email for your domain. It is one of the three core email authentication methods, and a missing or broken SPF record is a common reason legitimate email lands in spam.',
    sections: [
      { heading: 'How SPF works', paragraphs: ['When a server receives an email claiming to be from your domain, it looks up your SPF record and checks whether the sending server is on the authorised list. If not, the message is more likely to be filtered or rejected.'] },
      { heading: 'What an SPF record looks like', paragraphs: ['An SPF record is a DNS TXT record that starts with v=spf1 and ends with an "all" mechanism, for example: v=spf1 include:_spf.google.com ~all. The includes list the services allowed to send as you.'] },
      { heading: 'Check your SPF record', paragraphs: ['Use our free SPF checker to confirm your record exists and is valid. A domain must have exactly one SPF record, and it should stay under 10 DNS lookups.'] },
    ],
    faqs: [
      { q: 'Is SPF enough on its own?', a: 'No — SPF should be combined with DKIM and DMARC for full protection and best deliverability.' },
      { q: 'What does ~all mean in SPF?', a: 'The ~all (softfail) tells receivers to accept but mark unauthorised mail. -all (hardfail) tells them to reject it outright.' },
    ],
  },
  {
    slug: 'how-to-set-up-spf-record',
    keyword: 'How to Set Up SPF Record',
    title: 'How to Set Up an SPF Record (Step by Step) | BounceTrap',
    metaDescription: 'Step-by-step guide to creating an SPF record for your domain. Add the right TXT record, include your senders, and avoid the 10-lookup limit.',
    h1: 'How to Set Up an SPF Record',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'Setting up an SPF record tells the world which servers can send email for your domain. Here is how to create one correctly and avoid the common mistakes that break it.',
    sections: [
      { heading: 'Step 1: List your sending sources', paragraphs: ['Write down every service that sends email as your domain — your email host (Google Workspace, Microsoft 365), your marketing platform, your CRM, your transactional provider.'] },
      { heading: 'Step 2: Build the record', paragraphs: ['Combine each source\'s include mechanism into one record: v=spf1 include:_spf.google.com include:sendgrid.net ~all. Use exactly one SPF record per domain — multiple records cause SPF to fail.'] },
      { heading: 'Step 3: Add it to DNS and verify', paragraphs: ['Publish it as a TXT record at your root domain, then confirm it with our free SPF checker. Keep total DNS lookups under 10 or SPF will return a permerror.'] },
    ],
    faqs: [
      { q: 'Where do I add the SPF record?', a: 'In your DNS provider\'s control panel, as a TXT record on your root domain (the @ or blank host).' },
      { q: 'How long until SPF takes effect?', a: 'DNS changes typically propagate within minutes to a few hours.' },
    ],
  },
  {
    slug: 'what-is-dkim',
    keyword: 'What Is DKIM',
    title: 'What Is DKIM? DomainKeys Identified Mail Explained | BounceTrap',
    metaDescription: 'What is DKIM and how does it improve deliverability? A clear guide to DomainKeys Identified Mail and email signing, with a free DKIM checker.',
    h1: 'What Is DKIM (DomainKeys Identified Mail)?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'DKIM, or DomainKeys Identified Mail, adds a cryptographic signature to every email you send so receiving servers can verify the message really came from you and was not altered in transit. It is a core pillar of email authentication.',
    sections: [
      { heading: 'How DKIM works', paragraphs: ['You publish a public key in your DNS. Your mail server signs each outgoing message with the matching private key, and receivers verify the signature against your published key. A valid signature builds trust and boosts deliverability.'] },
      { heading: 'DKIM selectors', paragraphs: ['DKIM keys live at a selector, a label that lets you run multiple keys, e.g. google._domainkey.yourdomain.com. Your provider tells you which selector to use.'] },
      { heading: 'Check your DKIM', paragraphs: ['Use our free DKIM checker to confirm your signing is set up on the common selectors. If it is not found, get the exact selector from your email provider.'] },
    ],
    faqs: [
      { q: 'Does DKIM stop spoofing?', a: 'DKIM proves a message was not tampered with and came from an authorised key. Combined with DMARC, it strongly protects against spoofing.' },
      { q: 'Do I need DKIM if I have SPF?', a: 'Yes — they protect different things. Use SPF, DKIM and DMARC together.' },
    ],
  },
  {
    slug: 'how-to-set-up-dkim',
    keyword: 'How to Set Up DKIM',
    title: 'How to Set Up DKIM for Your Domain | BounceTrap',
    metaDescription: 'Step-by-step guide to enabling DKIM signing for your domain. Generate the key, add the DNS record, and verify it for free.',
    h1: 'How to Set Up DKIM',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'DKIM signing is usually enabled in your email provider, which gives you a DNS record to publish. Here is the general process.',
    sections: [
      { heading: 'Step 1: Enable DKIM in your provider', paragraphs: ['In Google Workspace, Microsoft 365, SendGrid or your ESP, turn on DKIM/email authentication. The provider generates a key and gives you a TXT record and selector.'] },
      { heading: 'Step 2: Add the DNS record', paragraphs: ['Publish the TXT record at the selector they specify, e.g. selector._domainkey.yourdomain.com. Copy the value exactly — DKIM keys are long and unforgiving of typos.'] },
      { heading: 'Step 3: Verify', paragraphs: ['Allow DNS to propagate, then confirm signing works with our free DKIM checker or by sending a test and inspecting the headers.'] },
    ],
    faqs: [
      { q: 'Can I have multiple DKIM keys?', a: 'Yes — use different selectors for different sending services on the same domain.' },
      { q: 'My DKIM is not found — why?', a: 'It is published at a provider-specific selector. Check your provider for the exact selector name.' },
    ],
  },
  {
    slug: 'what-is-dmarc',
    keyword: 'What Is DMARC',
    title: 'What Is DMARC? Policy & Reporting Explained | BounceTrap',
    metaDescription: 'What is DMARC and why does every domain need it? A plain guide to DMARC policy, reporting and protection against spoofing, with a free DMARC checker.',
    h1: 'What Is DMARC?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'DMARC ties SPF and DKIM together and tells receiving servers what to do with mail that fails authentication. It is the strongest protection against someone spoofing your domain, and it gives you reports on who is sending as you.',
    sections: [
      { heading: 'How DMARC works', paragraphs: ['DMARC checks that a message passes SPF or DKIM and that the domains align. Its policy then tells receivers how to handle failures, and its reporting address collects data on all mail claiming to be from you.'] },
      { heading: 'The DMARC policy levels', paragraphs: ['p=none monitors only, p=quarantine sends failures to spam, and p=reject blocks them entirely. Start at none, then tighten as your legitimate mail consistently passes.'] },
      { heading: 'Check your DMARC', paragraphs: ['Use our free DMARC checker to see your current policy. The record lives at _dmarc.yourdomain.com and starts with v=DMARC1.'] },
    ],
    faqs: [
      { q: 'Is DMARC required?', a: 'Major providers like Gmail and Yahoo now require DMARC for bulk senders. Every sending domain should have at least a p=none record.' },
      { q: 'What is a safe DMARC policy to start with?', a: 'Start with p=none to monitor without affecting delivery, then move to quarantine and reject.' },
    ],
  },
  {
    slug: 'dmarc-policy-explained',
    keyword: 'DMARC Policy',
    title: 'DMARC Policy: none vs quarantine vs reject | BounceTrap',
    metaDescription: 'Understand DMARC policies — none, quarantine and reject. Learn which to use, how to move between them safely, and check yours free.',
    h1: 'DMARC Policy: none vs quarantine vs reject',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'Your DMARC policy (the p= tag) decides what happens to email that fails authentication. Choosing the right one — and moving through them in order — is how you roll out DMARC without blocking your own mail.',
    sections: [
      { heading: 'p=none (monitor)', paragraphs: ['Takes no action but sends you reports. Use it first to see who is sending as your domain and confirm your legitimate mail passes.'] },
      { heading: 'p=quarantine', paragraphs: ['Sends failing mail to the spam folder. Move here once your real mail consistently passes SPF or DKIM with alignment.'] },
      { heading: 'p=reject', paragraphs: ['Blocks failing mail entirely — the strongest protection against spoofing. Move here once quarantine has run cleanly for a while.'] },
    ],
    faqs: [
      { q: 'How long should I stay on p=none?', a: 'Long enough to confirm all your legitimate senders pass — typically a few weeks of clean reports.' },
      { q: 'Will p=reject block my real emails?', a: 'Only if they fail authentication. Make sure every legitimate sender passes SPF or DKIM before moving to reject.' },
    ],
  },
  {
    slug: 'spf-vs-dkim-vs-dmarc',
    keyword: 'SPF vs DKIM vs DMARC',
    title: 'SPF vs DKIM vs DMARC: What’s the Difference? | BounceTrap',
    metaDescription: 'SPF vs DKIM vs DMARC explained simply. Learn what each does, how they work together, and why you need all three for deliverability.',
    h1: 'SPF vs DKIM vs DMARC',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'SPF, DKIM and DMARC are the three pillars of email authentication. They are often confused, but each does a distinct job — and you need all three working together for the best deliverability and protection against spoofing.',
    comparisonTable: {
      columns: ['', 'What it does', 'Where it lives'],
      rows: [
        ['SPF', 'Lists which servers may send for your domain', 'TXT record on your domain'],
        ['DKIM', 'Cryptographically signs each message', 'TXT record at a selector'],
        ['DMARC', 'Tells receivers how to handle failures + reports', 'TXT at _dmarc.yourdomain.com'],
      ],
    },
    sections: [
      { heading: 'How they work together', paragraphs: ['SPF authorises servers, DKIM signs messages, and DMARC sets the policy and alignment that tie the two together. DMARC depends on SPF and DKIM, which is why all three matter.'] },
      { heading: 'Check all three free', paragraphs: ['Use our free SPF, DKIM and DMARC checkers to confirm each is set up correctly for your domain.'] },
    ],
    faqs: [
      { q: 'Which is most important?', a: 'They work as a system — but DMARC is what enforces protection, and it requires SPF and DKIM to function.' },
      { q: 'Do I need all three?', a: 'Yes. Major mailbox providers now expect all three for reliable bulk delivery.' },
    ],
  },
  {
    slug: 'why-are-my-emails-going-to-spam',
    keyword: 'Why Are My Emails Going to Spam',
    title: 'Why Are My Emails Going to Spam? (And How to Fix It) | BounceTrap',
    metaDescription: 'Emails landing in spam? Here are the real causes — authentication, reputation, list quality — and exactly how to fix each one.',
    h1: 'Why Are My Emails Going to Spam?',
    readTime: '6 min read',
    publishedAt: '2026-06-04',
    intro: 'When your emails land in spam, it is almost always one of a handful of causes. Work through them in order and you will find — and fix — the problem.',
    sections: [
      { heading: '1. Missing or broken authentication', paragraphs: ['The most common cause. Confirm SPF, DKIM and DMARC all pass using our free checkers. Without them, providers do not trust your mail.'] },
      { heading: '2. A dirty list causing bounces', paragraphs: ['Sending to invalid addresses spikes your bounce rate and tanks your reputation. Verify your list before every send to remove dead addresses.'] },
      { heading: '3. Poor sender reputation or blacklisting', paragraphs: ['Check whether your domain or IP is blacklisted, and review your complaint rate. A history of spam complaints sends you straight to the junk folder.'] },
      { heading: '4. Spammy content and sending habits', paragraphs: ['Sudden volume spikes, misleading subject lines, and image-heavy emails with little text all trigger filters. Warm up new domains and keep content honest.'] },
    ],
    faqs: [
      { q: 'How do I stop my emails going to spam?', a: 'Authenticate your domain (SPF/DKIM/DMARC), verify your list to cut bounces, and maintain a low complaint rate.' },
      { q: 'Can one bad send hurt my deliverability?', a: 'Yes — a single high-bounce or high-complaint campaign can damage your reputation for weeks. Verify before you send.' },
    ],
  },

  // ── REPUTATION & INBOX ────────────────────────────────────────────────────
  {
    slug: 'sender-reputation',
    keyword: 'Sender Reputation',
    title: 'What Is Sender Reputation & How to Improve It | BounceTrap',
    metaDescription: 'Sender reputation decides whether you reach the inbox. Learn what affects it and how to improve your sender score, with free reputation tools.',
    h1: 'What Is Sender Reputation?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'Sender reputation is a score mailbox providers assign to your sending domain and IP based on your history. A good reputation lands you in the inbox; a poor one sends you to spam — even to your engaged subscribers.',
    sections: [
      { heading: 'What affects sender reputation', paragraphs: ['The biggest factors are your bounce rate, spam complaint rate, whether you hit spam traps, and how recipients engage with your mail.'], list: ['Low bounce rate (verify your list)', 'Low spam complaints', 'No spam-trap hits', 'Consistent, engaged sending'] },
      { heading: 'How to improve it', paragraphs: ['Verify your list before sending, remove inactive subscribers, authenticate your domain, and warm up new sending domains gradually. Monitor your domain reputation over time to catch problems early.'] },
    ],
    faqs: [
      { q: 'How do I check my sender reputation?', a: 'Monitor your domain reputation and blacklist status, and watch your bounce and complaint rates in your ESP.' },
      { q: 'How long does it take to recover a damaged reputation?', a: 'Weeks of consistent, clean sending. Prevention — verifying lists — is far easier than recovery.' },
    ],
  },
  {
    slug: 'domain-reputation',
    keyword: 'Domain Reputation',
    title: 'Domain Reputation: What It Is & How to Check It | BounceTrap',
    metaDescription: 'Your domain reputation directly affects inbox placement. Learn what it is, what hurts it, and how to monitor it with free tools.',
    h1: 'What Is Domain Reputation?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'Domain reputation is how mailbox providers judge the trustworthiness of your sending domain. Unlike IP reputation, it follows your domain everywhere — so it is worth protecting carefully.',
    sections: [
      { heading: 'What shapes domain reputation', paragraphs: ['Authentication, bounce and complaint rates, spam-trap hits, and engagement all feed into it. A clean, authenticated domain sending to verified recipients builds a strong reputation.'] },
      { heading: 'How to monitor and protect it', paragraphs: ['Track your domain reputation and blacklist status over time, verify lists before sending, and warm up new domains. Catching a dip early lets you fix it before deliverability collapses.'] },
    ],
    faqs: [
      { q: 'Is domain or IP reputation more important?', a: 'Both matter, but domain reputation follows you across IPs and is increasingly weighted by providers.' },
      { q: 'How do I check domain reputation?', a: 'Monitor blacklist status and engagement metrics, and use a reputation monitoring tool to track it over time.' },
    ],
  },
  {
    slug: 'ip-reputation',
    keyword: 'IP Reputation',
    title: 'IP Reputation for Email: What It Is & How to Improve It | BounceTrap',
    metaDescription: 'IP reputation affects whether your emails reach the inbox. Learn what it is, how warming works, and how to keep your sending IP clean.',
    h1: 'What Is IP Reputation?',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'IP reputation is the trust score attached to the IP address you send email from. A poor IP reputation — often from blacklisting or spam complaints — gets your mail blocked or filtered.',
    sections: [
      { heading: 'Dedicated vs shared IPs', paragraphs: ['On a shared IP, other senders affect your reputation. On a dedicated IP, you control it entirely but must warm it up before sending at volume.'] },
      { heading: 'How to protect IP reputation', paragraphs: ['Warm up new IPs gradually, keep bounce and complaint rates low by verifying lists, and check your IP against blacklists regularly.'] },
    ],
    faqs: [
      { q: 'How do I check if my IP is blacklisted?', a: 'Use a blacklist checker to scan your sending IP against major DNSBLs.' },
      { q: 'What is IP warming?', a: 'Gradually increasing send volume on a new IP so providers build trust before you send at full scale.' },
    ],
  },
  {
    slug: 'how-to-improve-email-deliverability',
    keyword: 'Improve Email Deliverability',
    title: 'How to Improve Email Deliverability: 10 Proven Steps | BounceTrap',
    metaDescription: 'Ten proven steps to improve email deliverability — from authentication and list verification to warming and engagement. Reach the inbox.',
    h1: 'How to Improve Email Deliverability',
    readTime: '6 min read',
    publishedAt: '2026-06-04',
    intro: 'Improving deliverability comes down to a repeatable set of habits. Here are the ten steps that have the biggest impact on inbox placement.',
    sections: [
      { heading: 'The 10 steps', paragraphs: ['Work through these in order — the first few have the biggest effect.'], list: [
        'Verify your list before every send',
        'Set up SPF, DKIM and DMARC',
        'Use double opt-in for new subscribers',
        'Remove inactive and unengaged contacts',
        'Warm up new domains and IPs gradually',
        'Keep a consistent sending volume',
        'Monitor blacklists and domain reputation',
        'Make unsubscribing easy (and honour it fast)',
        'Avoid spammy subject lines and content',
        'Segment and send relevant, engaging email',
      ] },
    ],
    faqs: [
      { q: 'What improves deliverability the most?', a: 'Verifying your list to cut bounces and authenticating your domain are the two highest-impact actions.' },
      { q: 'How fast will I see results?', a: 'List verification helps immediately; reputation improvements build over a few weeks of clean sending.' },
    ],
  },
  {
    slug: 'inbox-placement',
    keyword: 'Inbox Placement',
    title: 'Inbox Placement: What It Is & How to Improve It | BounceTrap',
    metaDescription: 'Inbox placement is the share of your emails that reach the inbox vs spam. Learn what drives it and how to test and improve your placement rate.',
    h1: 'What Is Inbox Placement?',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'Inbox placement is the percentage of your delivered emails that actually land in the inbox rather than the spam or promotions folder. It is a more honest measure of deliverability than delivery rate alone.',
    sections: [
      { heading: 'Delivery rate vs inbox placement', paragraphs: ['An email can be "delivered" but still sit in spam. Inbox placement measures where it actually lands — which is what matters for opens and revenue.'] },
      { heading: 'How to improve inbox placement', paragraphs: ['Authenticate your domain, verify your list, keep engagement high, and test placement across providers before big campaigns.'] },
    ],
    faqs: [
      { q: 'What is a good inbox placement rate?', a: '90%+ is strong. Below that, look at authentication, reputation and list quality.' },
      { q: 'How do I test inbox placement?', a: 'Send to seed accounts across Gmail, Outlook and Yahoo and check where the message lands.' },
    ],
  },
  {
    slug: 'email-blacklist-removal',
    keyword: 'Email Blacklist Removal',
    title: 'Email Blacklist Removal: How to Get Delisted | BounceTrap',
    metaDescription: 'On an email blacklist? Learn how DNSBLs work, why you were listed, and the exact steps to get your domain or IP delisted. Free blacklist checker.',
    h1: 'How to Get Off an Email Blacklist',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'If your domain or sending IP lands on a blacklist (DNSBL), mailbox providers will block or filter your email. Here is how to find out, fix the cause, and get delisted.',
    sections: [
      { heading: 'Step 1: Confirm the listing', paragraphs: ['Use our free blacklist checker to scan your domain and mail-server IPs against major DNSBLs and see exactly where you are listed.'] },
      { heading: 'Step 2: Fix the root cause', paragraphs: ['Common causes are a compromised account, sending to spam traps, or a high complaint rate from a dirty list. Verify and clean your list, secure your accounts, and authenticate your domain.'] },
      { heading: 'Step 3: Request delisting', paragraphs: ['Visit the blacklist\'s website and submit a removal request. Some delist automatically after a clean period; others require a manual request.'] },
    ],
    faqs: [
      { q: 'Why was I blacklisted?', a: 'Usually spam complaints, spam-trap hits, a compromised account, or a poor-quality list. Verifying your list prevents most of these.' },
      { q: 'How long does delisting take?', a: 'Anywhere from automatic (after a clean period) to a few days for manual requests.' },
    ],
  },

  // ── SMTP & BOUNCES ──────────────────────────────────────────────────────
  {
    slug: 'what-is-smtp',
    keyword: 'What Is SMTP',
    title: 'What Is SMTP? Simple Mail Transfer Protocol Explained | BounceTrap',
    metaDescription: 'What is SMTP and how does email actually get delivered? A plain-English guide to the Simple Mail Transfer Protocol and how verification uses it.',
    h1: 'What Is SMTP?',
    readTime: '5 min read',
    publishedAt: '2026-06-04',
    intro: 'SMTP, the Simple Mail Transfer Protocol, is the standard that mail servers use to send and relay email across the internet. Understanding it helps explain how email is delivered — and how email verification confirms an address without sending a message.',
    sections: [
      { heading: 'How SMTP delivers email', paragraphs: ['Your mail server looks up the recipient domain\'s MX records, connects to the mail server, and exchanges a series of commands (EHLO, MAIL FROM, RCPT TO, DATA) to hand over the message.'] },
      { heading: 'How verification uses SMTP', paragraphs: ['Email verifiers begin this same handshake to check whether a mailbox exists, but stop before the DATA step — so they confirm the address without ever delivering a message.'] },
    ],
    faqs: [
      { q: 'What port does SMTP use?', a: 'Port 587 for submission with STARTTLS, 465 for implicit TLS, and 25 for server-to-server relay.' },
      { q: 'Is SMTP secure?', a: 'Modern SMTP uses TLS encryption. Always use port 587 or 465 with TLS for sending.' },
    ],
  },
  {
    slug: 'smtp-ports',
    keyword: 'SMTP Ports',
    title: 'SMTP Ports Explained: 25, 465, 587 and 2525 | BounceTrap',
    metaDescription: 'Which SMTP port should you use — 25, 465, 587 or 2525? A clear guide to each port, when to use it, and TLS. Free SMTP test tool.',
    h1: 'SMTP Ports: 25, 465, 587 and 2525',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'SMTP uses several ports for different purposes. Picking the right one — and the right encryption — matters for sending reliably and securely.',
    comparisonTable: {
      columns: ['Port', 'Use', 'Encryption'],
      rows: [
        ['587', 'Email submission (recommended)', 'STARTTLS'],
        ['465', 'Email submission (legacy/implicit)', 'Implicit TLS'],
        ['25', 'Server-to-server relay', 'Optional (often blocked for submission)'],
        ['2525', 'Alternative submission', 'STARTTLS'],
      ],
    },
    sections: [
      { heading: 'Which port should I use?', paragraphs: ['For sending email from an app or client, use 587 with STARTTLS. Use 2525 as a fallback if 587 is blocked. Avoid 25 for submission — most networks block it to fight spam.'] },
      { heading: 'Test your SMTP server', paragraphs: ['Use our free SMTP test tool to check connectivity, STARTTLS, certificate validity and supported auth methods on any port.'] },
    ],
    faqs: [
      { q: 'Is port 587 or 465 better?', a: 'Port 587 with STARTTLS is the modern standard. 465 (implicit TLS) still works and is fine to use.' },
      { q: 'Why is port 25 blocked?', a: 'ISPs block port 25 for submission to reduce spam from compromised machines. Use 587 instead.' },
    ],
  },
  {
    slug: 'hard-bounce-vs-soft-bounce',
    keyword: 'Hard Bounce vs Soft Bounce',
    title: 'Hard Bounce vs Soft Bounce: What’s the Difference? | BounceTrap',
    metaDescription: 'Hard bounce vs soft bounce explained. Learn what causes each, which hurts your reputation most, and how to prevent them.',
    h1: 'Hard Bounce vs Soft Bounce',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'Not all bounces are equal. A hard bounce is permanent and damages your reputation; a soft bounce is temporary. Knowing the difference helps you protect your deliverability.',
    comparisonTable: {
      columns: ['', 'Hard bounce', 'Soft bounce'],
      rows: [
        ['Cause', 'Address/domain does not exist', 'Temporary (full mailbox, server down)'],
        ['Permanent?', 'Yes', 'No — may succeed later'],
        ['Reputation impact', 'High', 'Low'],
        ['Action', 'Remove immediately', 'Retry, remove if persistent'],
      ],
    },
    sections: [
      { heading: 'Why hard bounces are dangerous', paragraphs: ['Hard bounces tell mailbox providers you are sending to addresses you should not have. Too many and your reputation drops fast. Verifying your list removes the addresses that hard bounce before you send.'] },
    ],
    faqs: [
      { q: 'How do I prevent hard bounces?', a: 'Verify your list before sending to remove invalid addresses, and use double opt-in to stop typos entering your list.' },
      { q: 'Should I remove soft bounces?', a: 'Retry them a few times; if they keep soft-bouncing, remove them as they may be abandoned.' },
    ],
  },
  {
    slug: 'why-do-emails-bounce',
    keyword: 'Why Do Emails Bounce',
    title: 'Why Do Emails Bounce? Common Causes & Fixes | BounceTrap',
    metaDescription: 'Why do emails bounce? The common causes — invalid addresses, full mailboxes, blocked senders — and how to stop bounces before they happen.',
    h1: 'Why Do Emails Bounce?',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'An email bounces when it cannot be delivered. The causes range from permanent (the address does not exist) to temporary (the mailbox is full). Here is what causes bounces and how to prevent them.',
    sections: [
      { heading: 'Common bounce causes', paragraphs: ['Most bounces come from a handful of issues:'], list: [
        'The address does not exist (typo or fake)',
        'The domain has no mail servers (no MX records)',
        'The mailbox is full (temporary)',
        'The sender is blocked or blacklisted',
        'The message was flagged as spam',
      ] },
      { heading: 'How to prevent bounces', paragraphs: ['The biggest lever is list verification — it removes invalid addresses and dead domains before you send. Authenticating your domain prevents bounces caused by being blocked.'] },
    ],
    faqs: [
      { q: 'How do I stop emails bouncing?', a: 'Verify your list to remove invalid addresses, and authenticate your domain so you are not blocked.' },
      { q: 'What bounce rate is too high?', a: 'Above 2% is a warning sign; above 5% risks suspension by most email platforms.' },
    ],
  },
  {
    slug: 'what-is-a-catch-all-email',
    keyword: 'Catch-All Email',
    title: 'What Is a Catch-All Email Address? | BounceTrap',
    metaDescription: 'What is a catch-all (accept-all) email domain, and why does it make verification tricky? Learn how to handle catch-all addresses safely.',
    h1: 'What Is a Catch-All Email Address?',
    readTime: '4 min read',
    publishedAt: '2026-06-04',
    intro: 'A catch-all (or accept-all) domain accepts email sent to any address at that domain, even ones that do not exist. This makes catch-all addresses harder to verify — and riskier to send to.',
    sections: [
      { heading: 'Why catch-all domains are tricky', paragraphs: ['Because the server accepts every address, an SMTP check cannot confirm whether a specific mailbox really exists. Verifiers flag these as "catch-all" or "risky" rather than valid.'] },
      { heading: 'How to handle them', paragraphs: ['Treat catch-all addresses as risky: send to them cautiously, monitor engagement, and avoid them for cold outreach where a bounce is costly. BounceTrap clearly flags catch-all results so you can decide.'] },
    ],
    faqs: [
      { q: 'Are catch-all emails valid?', a: 'They may be — but it cannot be confirmed by verification, so they carry a higher bounce risk than confirmed-valid addresses.' },
      { q: 'Should I send to catch-all addresses?', a: 'With caution. They are fine for engaged audiences but risky for cold outreach.' },
    ],
  },
  {
    slug: 'what-is-a-role-based-email',
    keyword: 'Role-Based Email',
    title: 'What Is a Role-Based Email Address? | BounceTrap',
    metaDescription: 'What is a role-based email like info@ or support@, and should you send to them? Learn why they are flagged risky and how to handle them.',
    h1: 'What Is a Role-Based Email Address?',
    readTime: '3 min read',
    publishedAt: '2026-06-04',
    intro: 'A role-based email address belongs to a function rather than a person — like info@, support@, admin@ or sales@. They are valid addresses but carry higher risk for marketing, so verifiers flag them.',
    sections: [
      { heading: 'Why role-based addresses are risky', paragraphs: ['They are often shared inboxes or distribution lists, so they get lower engagement and higher complaint rates. Some providers treat mail to them more harshly.'] },
      { heading: 'How to handle them', paragraphs: ['For transactional mail they are fine. For marketing and cold outreach, consider excluding them or treating them as low priority. BounceTrap flags role-based addresses so you can filter them.'] },
    ],
    faqs: [
      { q: 'Should I email role-based addresses?', a: 'It depends on context — fine for support and transactional mail, risky for cold outreach and marketing.' },
      { q: 'Are role-based emails invalid?', a: 'No, they are usually valid — just higher risk, so they are flagged separately.' },
    ],
  },
]
