// Email-provider data for programmatic "verify <provider> email" pages.
// Each provider has genuinely unique characteristics (catch-all behaviour,
// MX, quirks) so pages are differentiated — not thin doorway pages.

export const PROVIDERS = [
  {
    slug: 'gmail',
    name: 'Gmail',
    domains: ['gmail.com', 'googlemail.com'],
    mx: 'Google (aspmx.l.google.com)',
    keyword: 'verify gmail email',
    catchAll: false,
    quirks: 'Gmail does not run a catch-all server, so a proper SMTP check can reliably confirm whether a specific Gmail mailbox exists. Gmail also ignores dots and "+tags" in the local part (john.doe+news@gmail.com reaches john doe), which matters when deduplicating lists.',
    tips: [
      'Dots in the username are ignored — j.ohn@gmail.com and john@gmail.com are the same inbox',
      'Everything after a + is a tag and routes to the base address',
      'Gmail aggressively filters spam, so authentication (SPF/DKIM/DMARC) is essential',
    ],
  },
  {
    slug: 'outlook',
    name: 'Outlook / Hotmail',
    domains: ['outlook.com', 'hotmail.com', 'live.com', 'msn.com'],
    mx: 'Microsoft (outlook-com.olc.protection.outlook.com)',
    keyword: 'verify outlook email',
    catchAll: false,
    quirks: 'Microsoft consumer mailboxes (Outlook, Hotmail, Live, MSN) are hosted on the same infrastructure. Microsoft uses greylisting and rate-limiting that can make individual SMTP checks slower or inconclusive, so a quality verifier retries and interprets responses carefully.',
    tips: [
      'Outlook, Hotmail, Live and MSN all share Microsoft infrastructure',
      'Greylisting can cause temporary "unknown" results — retries improve accuracy',
      'Microsoft filtering is strict on reputation, so warm up new domains',
    ],
  },
  {
    slug: 'yahoo',
    name: 'Yahoo',
    domains: ['yahoo.com', 'yahoo.co.uk', 'ymail.com', 'rocketmail.com'],
    mx: 'Yahoo (mta5.am0.yahoodns.net)',
    keyword: 'verify yahoo email',
    catchAll: false,
    quirks: 'Yahoo Mail (including AOL, which shares its backend) enforces strict sender requirements and now requires DMARC for bulk senders. Yahoo addresses can usually be verified via SMTP, but Yahoo rate-limits aggressively.',
    tips: [
      'Yahoo and AOL share the same mail backend',
      'Yahoo requires DMARC for bulk senders — set it up before sending at volume',
      'Expect rate-limiting; a good verifier paces checks accordingly',
    ],
  },
  {
    slug: 'icloud',
    name: 'iCloud',
    domains: ['icloud.com', 'me.com', 'mac.com'],
    mx: 'Apple (mx01.mail.icloud.com)',
    keyword: 'verify icloud email',
    catchAll: false,
    quirks: 'Apple\'s iCloud Mail covers icloud.com, me.com and mac.com addresses. Apple is privacy-focused and its servers can return guarded SMTP responses, so verification favours providers that interpret Apple\'s behaviour correctly. Hide My Email aliases (privaterelay.appleid.com) forward to a real inbox.',
    tips: [
      'icloud.com, me.com and mac.com are all Apple iCloud Mail',
      'Apple "Hide My Email" aliases forward to a hidden real address',
      'Expect conservative SMTP responses — interpretation matters',
    ],
  },
  {
    slug: 'proton',
    name: 'Proton Mail',
    domains: ['protonmail.com', 'proton.me', 'pm.me'],
    mx: 'Proton (mail.protonmail.ch)',
    keyword: 'verify proton mail email',
    catchAll: false,
    quirks: 'Proton Mail is an encrypted, privacy-first provider. Its servers deliberately limit what verification can confirm, so Proton addresses sometimes return "unknown". MX and domain checks still confirm the domain is a valid Proton domain.',
    tips: [
      'protonmail.com, proton.me and pm.me are all Proton',
      'Privacy design can make individual mailbox checks inconclusive',
      'Domain and MX validity can always be confirmed',
    ],
  },
  {
    slug: 'zoho',
    name: 'Zoho Mail',
    domains: ['zoho.com', 'zohomail.com'],
    mx: 'Zoho (mx.zoho.com)',
    keyword: 'verify zoho email',
    catchAll: false,
    quirks: 'Zoho Mail hosts both free zoho.com addresses and custom business domains. Custom-domain Zoho accounts may be configured as catch-all by the domain owner, which a verifier will flag accordingly.',
    tips: [
      'Free Zoho addresses use zoho.com or zohomail.com',
      'Business domains on Zoho may be catch-all — check the flag',
      'MX records pointing to zoho.com confirm Zoho hosting',
    ],
  },
  {
    slug: 'aol',
    name: 'AOL',
    domains: ['aol.com', 'aim.com'],
    mx: 'Yahoo/AOL (mx.aol.com)',
    keyword: 'verify aol email',
    catchAll: false,
    quirks: 'AOL Mail runs on Yahoo\'s infrastructure since the two merged. Verification behaves like Yahoo — generally checkable via SMTP but rate-limited, with the same DMARC requirements for bulk senders.',
    tips: [
      'AOL shares Yahoo\'s mail backend',
      'Same DMARC requirements as Yahoo for bulk sending',
      'Many AOL addresses are long-standing and may be abandoned — verify engagement',
    ],
  },
  {
    slug: 'gmx',
    name: 'GMX',
    domains: ['gmx.com', 'gmx.net', 'gmx.de'],
    mx: 'GMX (mx00.gmx.net)',
    keyword: 'verify gmx email',
    catchAll: false,
    quirks: 'GMX is a popular free provider in Europe. Its addresses are generally verifiable via SMTP. As with most large free providers, list quality matters more than provider quirks.',
    tips: [
      'GMX is widely used in Germany and Europe',
      'Generally checkable via standard SMTP verification',
      'Watch for old, abandoned free addresses',
    ],
  },
  {
    slug: 'mail-ru',
    name: 'Mail.ru',
    domains: ['mail.ru', 'bk.ru', 'inbox.ru', 'list.ru'],
    mx: 'Mail.ru (mxs.mail.ru)',
    keyword: 'verify mail.ru email',
    catchAll: false,
    quirks: 'Mail.ru is a major Russian free provider covering several domains. Addresses are usually verifiable, though regional sending considerations and language targeting matter for engagement.',
    tips: [
      'mail.ru, bk.ru, inbox.ru and list.ru are all Mail.ru',
      'Generally verifiable via SMTP',
      'Consider regional and language relevance for engagement',
    ],
  },
  {
    slug: 'fastmail',
    name: 'Fastmail',
    domains: ['fastmail.com', 'fastmail.fm'],
    mx: 'Fastmail (in1-smtp.messagingengine.com)',
    keyword: 'verify fastmail email',
    catchAll: false,
    quirks: 'Fastmail is a paid, privacy-respecting provider popular with professionals and developers. It supports masked aliases and custom domains, so some Fastmail-hosted addresses use the customer\'s own domain rather than fastmail.com.',
    tips: [
      'Many Fastmail users send from their own custom domains',
      'Supports masked/alias addresses that forward to a real inbox',
      'Generally reliable to verify via SMTP',
    ],
  },
  {
    slug: 'yandex',
    name: 'Yandex',
    domains: ['yandex.com', 'yandex.ru', 'ya.ru'],
    mx: 'Yandex (mx.yandex.ru)',
    keyword: 'verify yandex email',
    catchAll: false,
    quirks: 'Yandex Mail is a large provider in Russia and CIS countries, also offering hosting for custom domains (Yandex 360). Free addresses use yandex.com, yandex.ru or ya.ru.',
    tips: [
      'yandex.com, yandex.ru and ya.ru are free Yandex addresses',
      'Yandex also hosts custom business domains',
      'Verifiable via standard SMTP checks',
    ],
  },
  {
    slug: 'office365',
    name: 'Microsoft 365 (Business)',
    domains: ['(custom business domains)'],
    mx: 'Microsoft (yourdomain-com.mail.protection.outlook.com)',
    keyword: 'verify office 365 email',
    catchAll: false,
    quirks: 'Many businesses run email on Microsoft 365 using their own domain, with MX records pointing to *.mail.protection.outlook.com. These behave like Outlook for verification — strict greylisting and reputation filtering — and the domain owner may enable catch-all.',
    tips: [
      'Identified by MX records ending in mail.protection.outlook.com',
      'Behaves like Outlook: greylisting and strict filtering',
      'Business domains may be configured catch-all — check the flag',
    ],
  },
  {
    slug: 'google-workspace',
    name: 'Google Workspace (Business)',
    domains: ['(custom business domains)'],
    mx: 'Google (aspmx.l.google.com)',
    keyword: 'verify google workspace email',
    catchAll: false,
    quirks: 'Google Workspace hosts business email on custom domains with Google\'s MX records (aspmx.l.google.com). Verification is generally reliable like Gmail, though the domain owner can enable a catch-all that accepts any address.',
    tips: [
      'Identified by Google MX records on a custom domain',
      'Reliable to verify, like consumer Gmail',
      'Catch-all may be enabled by the admin — check the flag',
    ],
  },
]

export function getProvider(slug) {
  return PROVIDERS.find((p) => p.slug === slug)
}
