# Generated by Django 5.1.4 on 2026-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_subscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='webhook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
