# Generated by Django 5.1.4 on 2026-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_paid_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_rewards_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_stamps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
